import React, { useEffect, useContext, useState,useRef } from "react";
import Head from "next/head";
import { LanguageContext } from "../LanguageContext";
import { useSession } from 'next-auth/react';
import Banner from "@/Component/Home/Banner";
import { parse } from "cookie";
import { fetchBanner, fetchRecentlyAdded } from "./api/api";
import FeaturedProduct from "@/Component/Home/FeaturedProduct";
export default function Home({bannerHome,reacentlyAdded}) {
  const { translations, code, dir } = useContext(LanguageContext);
console.log(reacentlyAdded)
  return (
    <>
      <Head>
        <title>M1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      
     
      <main>
        <section>
      <Banner bannerHome={bannerHome}/>
  <FeaturedProduct reacentlyAdded={reacentlyAdded}/>
      </section>
      </main>
    </>
  )
}
export async function getServerSideProps(context) {
  const { req,locale } = context;
  const cookies = parse(req.headers.cookie || "");
  const selectedLanguage = locale=='AR'?'1':'2';
  const page = 1; 
  const bannerHome = await fetchBanner();
const reacentlyAdded= await fetchRecentlyAdded(selectedLanguage);

  const propsToInspect = {
    bannerHome,
    reacentlyAdded
  };
  console.log("Props:", propsToInspect);

  return {
    props: propsToInspect,
  };
}

